server:
  port: 8080
  servlet:
    context-path: /BFF

spring:
  datasource:
    url: jdbc:mysql://192.168.31.22:3306/BFF?serverTimezone=Asia/Shanghai&useSSL=false
    username: appuser
    password: jianjian123
    driver-class-name: com.mysql.cj.jdbc.Driver